### ISSUE TITLE
Problema configuração TypeError: SiTef is not a constructor

### ISSUE THREAD

**Issue by joaodematejr** [danielccunha/node-sitef#5]
estou tentando configurar o protejo mas quando vou fazer const sitef = new SiTef(dlls) fica acusando esse erro.

const sitef = new SiTef(dlls)
              ^

TypeError: SiTef is not a constructor
    at Object.<anonymous> (C:\Users\joao\Desktop\node\index.js:6:15)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
PS C:\Users\joao\Desktop\node> 

![image](https://user-images.githubusercontent.com/17418041/120121839-16597900-c17c-11eb-964f-d60e825ed7a5.png)

**Comment by fefurst** [comment]
Olá. Sitef é exportado como default, para TS. Para nodejs, na linha que está dano problema, você pode usar:

`const SiTef = require('node-sitef').default;
`

**Comment by joaodematejr** [comment]
> Olá. Sitef é exportado como default, para TS. Para nodejs, na linha que está dano problema, você pode usar:
> 
> `const SiTef = require('node-sitef').default; `

Vou fazer o teste se funcionar fecho o comentário

**Comment by joaodematejr** [comment]
Funcionou, Muito Obrigado !!!
